package com.mathwithbros.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;

@DynamoDBTable( tableName = "Game" )
public class GameItem {

	private String gameID;
	private String p1_userName;
	private String p2_userName;
	private int p1_score;
	private int p2_score;
	
	@DynamoDBAutoGeneratedKey
	@DynamoDBHashKey
	public String getGameID() { return gameID; }
	public void setGameID( String gameID ) { this.gameID = gameID; }
	
	@DynamoDBAttribute
	public String getP1UserName() { return p1_userName; }
	public void setP1UserName( String p1_userName ) { this.p1_userName = p1_userName; }
	
	@DynamoDBAttribute
	public String getP2UserName() { return p2_userName; }
	public void setP2UserName( String p2_userName ) { this.p2_userName = p2_userName; }
	
	@DynamoDBAttribute
	public int getP1Score() { return p1_score; }
	public void setP1Score( int p1_score ) { this.p1_score = p1_score; }
	
	@DynamoDBAttribute
	public int getP2Score() { return p2_score; }
	public void setP2Score( int p2_score ) { this.p2_score = p2_score; }
}
